# Generated by Django 3.2.11 on 2022-01-18 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'required': 'error_message : This is required., error_code : 3'}, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'required': 'error_message : This already exists., error_code : 1', 'unique': 'error_message : This must be unique., error_code : 2'}, max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'required': 'error_message : This is required., error_code : 3'}, max_length=30)),
                ('code', models.CharField(error_messages={'required': 'error_message : This is required., error_code : 3', 'unique': 'error_message : This must be unique., error_code : 2'}, max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'required': 'error_message : This already exists., error_code : 1'}, max_length=30)),
                ('price', models.DecimalField(decimal_places=4, default=0.0, max_digits=100)),
                ('agent_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flights.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(verbose_name='departure_time')),
                ('arrival_time', models.DateTimeField(verbose_name='arrival_time')),
                ('duration', models.IntegerField(default=60)),
                ('stops', models.IntegerField(default=0)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='airline', to='flights.airline')),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leg_arrival_airport', to='flights.airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leg_departure_airport', to='flights.airport')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legs', to='flights.itinerary')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flights.airline'),
        ),
    ]
